function buildLevel1() {
  return new Level(
    [new Endboss()],
    [
      new Enemy1(),
      new Enemy1(),
      new Enemy1(),
      new Enemy2(),
      new Enemy2(),
      new Enemy2(),
    ],
    [
      new Cloud("assets/img/clouds/clouds2.png", 0),
      new Cloud("assets/img/clouds/clouds2.png", 720),
    ],
    [
      new BackgroundObject("assets/img/background/sky.png", -720, 0), // path, x,
      new BackgroundObject("assets/img/background/rocks.png", -720, 0),
      new BackgroundObject("assets/img/background/rocks2.png", -720, 0),
      new BackgroundObject("assets/img/background/rocks3.png", -720, 0),
      new BackgroundObject(
        "assets/img/background/ground_tile07.png",
        -720,
        340,
      ),
      new BackgroundObject("assets/img/background/sky.png", 0, 0), // path, x,
      new BackgroundObject("assets/img/background/rocks.png", 0, 0),
      new BackgroundObject("assets/img/background/rocks2.png", 0, 0),
      new BackgroundObject("assets/img/background/rocks3.png", 0, 0),
      new BackgroundObject("assets/img/background/ground_tile07.png", 0, 340),
      new BackgroundObject("assets/img/background/sky.png", 720, 0), // path, x,
      new BackgroundObject("assets/img/background/rocks.png", 720, 0),
      new BackgroundObject("assets/img/background/rocks2.png", 720, 0),
      new BackgroundObject("assets/img/background/rocks3.png", 720, 0),
      new BackgroundObject("assets/img/background/ground_tile07.png", 720, 340),
      new BackgroundObject("assets/img/background/sky.png", 720 * 2, 0), // path, x,
      new BackgroundObject("assets/img/background/rocks.png", 720 * 2, 0),
      new BackgroundObject("assets/img/background/rocks2.png", 720 * 2, 0),
      new BackgroundObject("assets/img/background/rocks3.png", 720 * 2, 0),
      new BackgroundObject(
        "assets/img/background/ground_tile07.png",
        720 * 2,
        340,
      ),
      new BackgroundObject("assets/img/background/sky.png", 720 * 3, 0), // path, x,
      new BackgroundObject("assets/img/background/rocks.png", 720 * 3, 0),
      new BackgroundObject("assets/img/background/rocks2.png", 720 * 3, 0),
      new BackgroundObject("assets/img/background/rocks3.png", 720 * 3, 0),
      new BackgroundObject(
        "assets/img/background/ground_tile07.png",
        720 * 3,
        340,
      ),
    ],
    [
      new CollectableObjects(200, 300),
      new CollectableObjects(200 * 3, 300),
      new CollectableObjects(200 * 4, 300),
      new CollectableObjects(200 * 4.5, 300),
      new CollectableObjects(200 * 7, 300),
    ],
    [
      new CollectableStone(250, 350),
      new CollectableStone(250 * 1.5, 350),
      new CollectableStone(250 * 4, 350),
      new CollectableStone(250 * 4.5, 350),
      new CollectableStone(250 * 7, 350),
      new CollectableStone(250 * 8, 350),
    ],
  );
}
