const level1 = new Level(
  [new Enemy1(), new Enemy1(), new Enemy1(), new Endboss()],
  [
    new Cloud("assets/img/clouds/clouds2.png", 0),
    new Cloud("assets/img/clouds/clouds2.png", 720),
  ],
  [
    new BackgroundObject("assets/img/background/sky.png", -720, 0), // path, x,
    new BackgroundObject("assets/img/background/rocks.png", -720, 0),
    new BackgroundObject("assets/img/background/rocks2.png", -720, 0),
    new BackgroundObject("assets/img/background/rocks3.png", -720, 0),
    new BackgroundObject("assets/img/background/ground_tile07.png", -720, 340),
    new BackgroundObject("assets/img/background/sky.png", 0, 0), // path, x,
    new BackgroundObject("assets/img/background/rocks.png", 0, 0),
    new BackgroundObject("assets/img/background/rocks2.png", 0, 0),
    new BackgroundObject("assets/img/background/rocks3.png", 0, 0),
    new BackgroundObject("assets/img/background/ground_tile07.png", 0, 340),
    new BackgroundObject("assets/img/background/sky.png", 720, 0), // path, x,
    new BackgroundObject("assets/img/background/rocks.png", 720, 0),
    new BackgroundObject("assets/img/background/rocks2.png", 720, 0),
    new BackgroundObject("assets/img/background/rocks3.png", 720, 0),
    new BackgroundObject("assets/img/background/ground_tile07.png", 720, 340),
    new BackgroundObject("assets/img/background/sky.png", 720 * 2, 0), // path, x,
    new BackgroundObject("assets/img/background/rocks.png", 720 * 2, 0),
    new BackgroundObject("assets/img/background/rocks2.png", 720 * 2, 0),
    new BackgroundObject("assets/img/background/rocks3.png", 720 * 2, 0),
    new BackgroundObject(
      "assets/img/background/ground_tile07.png",
      720 * 2,
      340,
    ),
    new BackgroundObject("assets/img/background/sky.png", 720 * 3, 0), // path, x,
    new BackgroundObject("assets/img/background/rocks.png", 720 * 3, 0),
    new BackgroundObject("assets/img/background/rocks2.png", 720 * 3, 0),
    new BackgroundObject("assets/img/background/rocks3.png", 720 * 3, 0),
    new BackgroundObject(
      "assets/img/background/ground_tile07.png",
      720 * 3,
      340,
    ),
  ],
);
